### ISSUE TITLE
Plugin does not appear in list of available via Plugin Manager. 

### ISSUE THREAD

**Issue by nionio6915** [chatrat12/layerdisplay#2]
I was excited to see this plugin via the news, but could not find it via the plug in manager. 
I had to load it via the URL manually.  Here is the list of plugins while searching for "Layer" or similarly "LayerDisplay" .

I am on a minty fresh install of OctoPrint 1.3.9rc3 running on OctoPi 0.15.1.

![image](https://user-images.githubusercontent.com/17693150/42903600-f8c90dce-8a97-11e8-8d68-32018523c797.png)

**Comment by prgmatic** [comment]
Hmmm, that is interesting. ~~Not sure how to force the plugin manager to refresh.~~ (Click little wrench icon and then click 'Refresh list from repository') I clicked the little wrench up top and told it order by newest plugins. Here is what mine looks like:

![image](https://user-images.githubusercontent.com/251682/42904521-53d87fd2-8aa3-11e8-9c1b-d30511b075b3.png)

Are you missing more than just LayerDisplay?

**Comment by prgmatic** [comment]
Maybe a power cycle will force it to fetch the latest plugins. If all else fails, you can enter the following url into the '...from URL' box and click Install.

    https://github.com/chatrat12/layerdisplay/archive/master.zip

**Comment by prgmatic** [comment]
I figured out to fetch the latest plugins, click the little wrench and then click 'Refresh list from repository' 

![image](https://user-images.githubusercontent.com/251682/42905002-c38c1e14-8aa4-11e8-97f4-36f94dccefa4.png)

**Comment by prgmatic** [comment]
Going to close this, let me know if you are still having issues.
