### ISSUE TITLE
The number of layers is wrong

### ISSUE THREAD

**Issue by benland2** [chatrat12/layerdisplay#3]
The number of layers and the current layer are wrong.

For example:
In "Gcode viewer", I can see:
- Layer count: 118 printed
- Layer number: 12

In the Sidebar, I can see:
- Layer: 1 / 59

I use OctoPrint Version 1.3.9, LayerDisplay (0.3.0), printer Creality CR-10 .

What is the problem ?

**Comment by prgmatic** [comment]
Oh no! I'll look into it. Can I possibly get the gcode you were using?

**Comment by prgmatic** [comment]
Got my dev environment upgraded to 1.3.9 and layers are tracking properly on my test prints. My GCode parser may be incomplete. What slicer are you using?

**Comment by benland2** [comment]
I use Ultimaker Cura on Mac OS X.
I join my gcode file.


[PI3_Couvercle-cutted.gcode.zip](https://github.com/chatrat12/layerdisplay/files/2237739/PI3_Couvercle-cutted.gcode.zip)

**Comment by prgmatic** [comment]
Figured it out. My GCode analyzer was not detecting layer changes that occur beneath the previously recorded extrusion height. Your GCode raises the Z axis 15mm and then extrudes 3mm, The analyzer would not detect layers beneath that 15mm. I have resolved the issue. 0.3.1 release is up. You should now be able to update through the 'Software Update' tab in OctoPrint settings. 

Thank you so much for the bug report :)

**Comment by benland2** [comment]
It works. Thank you
