### ISSUE TITLE
After updating to the newest octoprint the layer is not showing any longer

### ISSUE THREAD

**Issue by 12345Josparky** [chatrat12/layerdisplay#9]
After updating to the newest octoprint the layer is not showing any longer on ender 3

**Comment by cstaab** [comment]
I've experienced this same issue on a Monoprice I3/Plus.  The only change that was made between layer display working and not working was updating Octoprint to 1.4.0.  now instead of displaying 
Layer: n / nnn it displays Layer:  -

**Comment by dshokouhi** [comment]
Probably related to #8 ?

**Comment by 12345Josparky** [comment]
> Probably related to #8 ?

Yes it probably is that was my guess to just don't know how to fix it. Doesn't look like this plugin has been worked on in a couple years so may not get fixed. Might just disable it or maybe get my programmer to look at it and see if he can fix it. either way not doing much good to leave it active for now. Hopefully the maker of it can figure it out.

**Comment by aerickson** [comment]
I've got a working fix with installation directions in #11.

**Comment by prgmatic** [comment]
Sorry for getting to this so late guys :( Looks like foosel warned me about it back in December but that seemed to have slipped through my inbox :O I merged @aerickson fix and pushed a new version. My printer is currently printing, once it's done I need to get on Octoprint 1.4 and test. Deploy then test, that's how software development works, right?

**Comment by prgmatic** [comment]
Would have helped if I had actually merged the `devel` branch into `master`. What am I even doing"? *face palm*. It seems to be all sorted out. Have a large print going with 600 layers. Will monitor, I don't expect anything to go wrong :D

Updated to 0.4.3 to get the working version
